### ISSUE TITLE
Feature request: use OAuth 2.0 for Devices in -headless mode

### ISSUE THREAD

**Issue by 0x1eaf** [astrada/google-drive-ocamlfuse#109]
There is a painless way to authenticate in headless mode:
https://developers.google.com/accounts/docs/OAuth2ForDevices

**Comment by w-flo** [comment]
Dirty workaround that worked for me:
- Backup /usr/bin/xdg-open
- Create new /usr/bin/xdg-open file, and make sure to mark it executable. Contents:
```
#!/bin/sh
echo $1 1>&2
exit 0
```
(Not sure if exit 0 is required, I guess not. Just make sure not to echo anything to STDOUT, that apparently makes google-drive-ocamlfuse think that something failed and exit instead of polling for access grant.)
- Run google-drive-ocamlfuse, which should print the URL and you can use your favourite web access method to go to that URL and grant access, then follow the usual docs. Don't forget to put the original xdg-open script back in place.

**Comment by astrada** [comment]
Unfortunately, it looks like OAuth 2.0 for TV and Limited Input Device Applications doesn't support Google Drive: https://developers.google.com/identity/protocols/OAuth2ForDevices#allowedscopes
