### ISSUE TITLE
Hanging in Nautilus since 0.5.18, killing process required

### ISSUE THREAD

**Issue by neilcsmith-net** [astrada/google-drive-ocamlfuse#135]
Since updating to 0.5.18 through the PPA on Ubuntu 14.04, Nautilus is hanging when viewing the home directory (which contains the mount point) or the drive itself.  Was working fine before the update.

Seems to work OK from a terminal until opening Nautilus, after which the ls command also hangs.

In all cases, killing google-drive-ocamlfuse then becomes the only option.

**Comment by astrada** [comment]
Are you mounting it automatically via /etc/fstab? If so, try adding `big_writes` to mount options. E.g.:

    gdfuse#default  /mnt/gdrive     fuse    uid=1000,gid=1000,big_writes     0       0

**Comment by neilcsmith-net** [comment]
No, I'm not.  Is that something that changed behaviour?  Can that be set in config?

**Comment by astrada** [comment]
No, I just added an option, but it should not affect normal use. I think the problem is that when you upgrade from one version to another, the application clears its cache. Try mounting your drive, then from the command line, run (in the directory where you mounted your drive):

    $ ls -R

This command scans recursively all your files (it will take some time), so that the cache can be rebuilt. Maybe this helps.

**Comment by neilcsmith-net** [comment]
Well, thought I'd try that, but sceptical that was the cause because I do clear the cache regularly (different problem with a file not being updated).  Anyway, even before trying that, it's now working fine. :confused: I assume that the update may have been a coincidence and this was actually some issue with the network connection with Drive.  If so, slightly concerning that it rendered the system unusable, even requiring REISUB at times.

However, as it's currently working I'll close this and keep an eye on it.

Many thanks for the great software and help!
