### ISSUE TITLE
Is it possible to install this on Synology NAS?

### ISSUE THREAD

**Issue by Rick7C2** [astrada/google-drive-ocamlfuse#138]
I have a Synology DS1812+ that I need to be able to mount my google drive on. 

I have no idea how to get this installed on synology. Is there a guide? Is it even possible?

**Comment by astrada** [comment]
> Is there a guide?

No, sorry.

> Is it even possible?

I think so, but I don't think it's easy. You have to compile everything on the NAS because it's based on PPC/ARM. Wouldn't it be easier to install google-drive-ocamlfuse on a standard Linux box and set a cron job to backup your Drive on the NAS? I don't think that mounting Drive directly on the NAS brings any benefit.

**Comment by astrada** [comment]
I published packages for armhf architecture (on Ubuntu) in the PPA. Maybe you can use them on Synology NAS.
