### ISSUE TITLE
Browser not opened when running google-drive-ocamlfuse

### ISSUE THREAD

**Issue by abrambailey** [astrada/google-drive-ocamlfuse#143]
I am running Linux Mint 17 64-bit with Linux kernel 3.13.0-36-generic

Installed via:
```
$ sudo add-apt-repository ppa:alessandro-strada/ppa
$ sudo apt-get update
$ sudo apt-get install google-drive-ocamlfuse
```
Here is the output for `google-drive-ocamlfuse -debug`
```
Starting application setup (label=default, base_dir=/home/funkdified/.gdfuse).
Opening log file: /home/funkdified/.gdfuse/default/gdfuse.log
```
gdfuse.log
```
[0.000195] TID=0: Setting up default filesystem...
[0.000247] TID=0: Loading configuration from /home/funkdified/.gdfuse/default/config...done
Saving configuration in /home/funkdified/.gdfuse/default/config...done
[0.000542] TID=0: Loading application state from /home/funkdified/.gdfuse/default/state...done
Current version: 0.5.18
Setting up cache db...done
Setting up CURL...done
Refresh token already present.
```
curl.log is empty

**Comment by astrada** [comment]
Looks like the application was successfully authorized. What happens if you start the command specifying the mount-point?

**Comment by abrambailey** [comment]
Got it working with the mount-point. But very slow. What I can do to in my config to speed things up?

**Comment by astrada** [comment]
If you have Google Docs in your root, setting `download_docs=false` in configuration would probably speed things up a bit.

**Comment by abrambailey** [comment]
Thanks, that definitely helped. Great work on this project :)

**Comment by farvardin** [comment]
hello,

I had the same problem. It seems I installed and authorised google-drive-ocamlfuse last year, but I didn't remember it :)

Anyway, mounting the google drive didn't work correctly, maybe because it was a previous version or the tokens were too old. 

I removed ~/.gdfuse/default/state and it authorised again, and it worked fine.

**Comment by FVFaleiro** [comment]
The @farvardin solution works for me too in Ubuntu 16.04. :)

**Comment by josuearisty** [comment]
Hi

Im using Ubuntu 17 and browser is not opening, I tried on a vps too and the same result, no browser.

Is this tool working right now?

Thanks

**Comment by anttiryt** [comment]
> Hi
> 
> Im using Ubuntu 17 and browser is not opening, I tried on a vps too and the same result, no browser.
> 

I had same problem, remote machine without desktop and DISPLAY empty. 

Seems it no longer runs www-browser but starts with firefox, google-chrome, chromium-browser. 

Well, anyway, running 

`DISPLAY=:4 google-drive-ocamlfuse`

( :4 being just any unused DISPLAY port. I guess it defaulted to :0 )

helped me to get forward. 

And if you get "X11 connection rejected because of wrong authentication" when running SNAP software like browser, use

`export XAUTHORITY=$HOME/.Xauthority`

( [src](https://unix.stackexchange.com/a/709789/12207) )
