### ISSUE TITLE
How does google-drive-ocamlfuse work?

### ISSUE THREAD

**Issue by socheon** [astrada/google-drive-ocamlfuse#167]
Does it creates a local copy and sync it with the remote copy in Google Drive? In other words, does it work like Dropbox? I want the files available offline, and then backup/sync the files with Google Drive, when I am online. Is google-drive-ocamlfuse suitable for this purpose? I am using Ubuntu.

**Comment by astrada** [comment]
No, it does not work like the Dropbox client, so you cannot access your files offline. Please check our another client (e.g. [this one](https://github.com/odeke-em/drive)).

**Comment by kir12** [comment]
Sorry to resurrect a dead thread, but does this mean ocamlfuse works _without_ directly taking up the server's main hard drive space?

**Comment by brancomat** [comment]
I'll try to reply in place of @astrada 

> does this mean that ocamlfuse works _without_ directly taking up the server's main hard drive space?

Almost, but not completely: it still has a cache directory (you can configure size and location, see https://github.com/astrada/google-drive-ocamlfuse/wiki/Configuration ).

But keep in mind that the `max_cache_size_mb` is ignored during uploads (because Drive API doesn't offer a method to upload portions of a file). That means: if you have to upload a 40Gb file you still need 40Gb of free space on the server.

See also #416 on this subject.
