### ISSUE TITLE
Support multithread download?

### ISSUE THREAD

**Issue by ittus** [astrada/google-drive-ocamlfuse#185]
Does **google-drive-ocamlfuse** support multithread downloading? 
What's happen if I have 2 processes which access to same file, is it download 2 times? If the file's size is big and os's scheduler switch between 2 processes, is the file downloaded again multi-times?

**Comment by astrada** [comment]
The default mode is single threaded, so there is no concurrency. If you use `-m` to activate multi-threading, there is the possibility that the file is downloaded 2 times but this scenario should be quite rare (the 2 processes have to start accessing the file *exactly* at the same time). To be sure (if you don't mind caching the files), you could use `stream_large_files=true`, so that you never download big files.

**Comment by ittus** [comment]
Thank @astrada. 
Are there any way to know/test it's working in multithread mode properly? I tried to use `stream_large_files=true` before but it seems slowdown downloading process.

**Comment by astrada** [comment]
> I tried to use stream_large_files=true before but it seems slowdown downloading process.

Sure, but it gets you more consistent results. It's a trade-off.

**Comment by astrada** [comment]
Pre-release [0.6.0](https://github.com/astrada/google-drive-ocamlfuse/releases/tag/v0.6.0) should address at least part of this issue. See this [comment](https://github.com/astrada/google-drive-ocamlfuse/issues/128#issuecomment-261799554) for further info.
