### ISSUE TITLE
How to turn off caching before upload (copying temporary file before sending to drive?)

### ISSUE THREAD

**Issue by MarioPL98** [astrada/google-drive-ocamlfuse#187]
Hi. When I try to upload a file, first it gets copied to ~/.gdfuse/default/cache then the upload starts. Is there any way to skip it and start uploading immediately? Thanks.

My question comes from here: http://forums.debian.net/viewtopic.php?f=10&t=129095&p=620132#p620132 , my last post describes everything.

**Comment by astrada** [comment]
Unfortunately it's not possible, because you need a whole file to begin uploading to Google Drive (via the API). You cannot upload just some bytes of the file, so you have to wait for the file to be completely copied to the local cache. You can check if other tools (e.g. https://github.com/odeke-em/drive), that don't use a FUSE backend, suit better your needs.

**Comment by MarioPL98** [comment]
Thanks. Will it work on debian 8?

**Comment by astrada** [comment]
I think so, if you can install the Go runtime, it should work.
