### ISSUE TITLE
Usage with rsync

### ISSUE THREAD

**Issue by JP-Ellis** [astrada/google-drive-ocamlfuse#21]
Hi,

I started using your program and it really seems great. I was wondering though whether using `rsync` is of any advantage for this in terms of bandwidth as I have noticed it to be quite slow.

Also, in my attempt with `rsync` and a few PDF files, I have found that I am unable to open them in Google Drive as it says that 

> **No preview available**
> This item was created with **google-drive-ocamlfuse**, a Google Drive app.
> Download this file or use one of the apps you have installed to open it.

also, the mime type of the PDF according to Google is `application/octet-stream`.

**Comment by aselvan** [comment]
I had the same issue with image files when I used rsync. After adding "--inplace" backup to Google Drive via google-drive-ocamlfuse works perfect with rsync. Thanks @astrada

**Comment by brancomat** [comment]
Sorry to comment a closed issue, still this is the best thread I've found on using rsync on google-drive-ocamlfuse (imho some suggestions of this issue should be promoted to a wiki page, @astrada I'd gladly help)

I generally see everyone experiencing some vaguely defined "slow" rating but I can't find something more specific: I'm uploading files with rsync at something less than 1.4 Mbps, I'm wondering:
 * is this considered "normal"?
 * are there any fine tunings that can increase upload speed? (besides the `--inplace` option)
 * (slightly OT) is this slowness due to google drive's api in general (meaning: there's no other way to significantly increase transfer speed to/from google drive)?

I'm aware that (quoting [this interesting thread](https://productforums.google.com/forum/#!msg/drive/fqj09cmUtz0/uKB4lUD8TO0J)) there hasn't been a "clear statement from Google's side about what upload speed is expected" so I guess it's difficult to talk numbers.

**Comment by astrada** [comment]
> imho some suggestions of this issue should be promoted to a wiki page, @astrada I'd gladly help

Sure! Feel free to create a new wiki page. Thanks!

 > is this considered "normal"?

I'm sorry, but I don't have a very stable connection (I'm on LTE that has very variable upload rate) so I can't measure a "normal" speed.

> are there any fine tunings that can increase upload speed? (besides the --inplace option)

You can test these options:
 * you can set a very high timeout in `metadata_cache_time=` so your cache doesn't risk to be invalidated
 * you can try multi-threading with `-m` (I'm still testing this option so it's not yet super-stable) even if rsync is single-theaded (but you can test [parallel](http://www.gnu.org/software/parallel/))
 * I'm still looking for some way to increase the maximum FUSE block size (that is 128KB)

> (slightly OT) is this slowness due to google drive's api in general (meaning: there's no other way to significantly increase transfer speed to/from google drive)?

I'm experiencing very variable transfer rates too, but I'm not sure this is due to Google or to my 4G provider.

**Comment by brancomat** [comment]
Thank you,
wiki page [created](https://github.com/astrada/google-drive-ocamlfuse/wiki/rsync)

I'm trying your suggestions, the rsync + parallel experiment went wrong: I was using [this approach](http://unix.stackexchange.com/questions/189878/parallelise-rsync-using-gnu-parallel) but after a while I got a lot of:
```
rsync error: errors selecting input/output files, dirs (code 3) at main.c(634) [Receiver=3.1.0]
rsync: ERROR: cannot stat destination "/my/ocamlfuse/mount/path": Transport endpoint is not connected (107)
```
Right now I've launched manually two separate instances of rsync on different subpath, so far so good but I'm not sure if this is affecting transfer speed

**Comment by astrada** [comment]
> wiki page created

Nice, thanks.

> rsync: ERROR: cannot stat destination "/my/ocamlfuse/mount/path": Transport endpoint is not connected (107)

OK, I will do a couple of tests.

Thanks for your feedback.

**Comment by brancomat** [comment]
It seems that the performance issues (and the "transport endpoint is not connected") might be related to the fact that I'm behind a ntlm authenticated proxy (I'm sorry I didn't mention that earlier, my bad). I repeated the test on the same network bypassing the proxy and speed improved almost tenfold. 
After around 100GB of data transfer I experienced a:
```
Device or resource busy (16)
rsync error: error in file IO (code 11) at receiver.c(856) [receiver=3.1.0]
```
But in that particular server I haven't still changed the `metadata_cache_time`, maybe it's because of that (?)

**Comment by astrada** [comment]
> But in that particular server I haven't still changed the metadata_cache_time, maybe it's because of that (?)

No, I don't think so. It's probably a bug (if you are using multi-threading) or (less likely) you received too many errors server side (each request is retried at most 10 times).
