### ISSUE TITLE
Issues with uploading PowerPoint files

### ISSUE THREAD

**Issue by bnieuwveld** [astrada/google-drive-ocamlfuse#214]
I'm not sure if this is a Google issue or an issue with this tool, and I also haven't tested it with any other file formats, but when I save a .pptx file, it syncs to Google Drive as a compressed archive. The workaround that I've found is to drag the .pptx file into the Google Drive web interface, at which point it recognises it as a PowerPoint file. Strange!

**Comment by astrada** [comment]
How do you save the .pptx? That's because I've copied a .pptx to my Google Drive and it was correctly detected as Power Point (mime type application/vnd.openxmlformats-officedocument.presentationml.presentation). If the program you use to save it, uses a temporary filename without the .pptx extesion, you could experience that issue.
