### ISSUE TITLE
Is it possible to get pre-compiled binaries in a zip?

### ISSUE THREAD

**Issue by Rick7C2** [astrada/google-drive-ocamlfuse#224]
I have a Synology DS1812+ that I can't seem to compile for.

I recently came across rclone and was able to download their pre-compiled amd64 binary and it works great on my synology using the below commands...

```
curl -O http://downloads.rclone.org/rclone-current-linux-amd64.zip
unzip rclone-current-linux-amd64.zip
cd rclone-current-linux-amd64
sudo cp rclone /usr/sbin/
sudo chown root:root /usr/sbin/rclone
```

Would google-drive-ocamlfuse work this way with a pre-compiled binary?

As you you can tell im not very good with linux.

**Comment by astrada** [comment]
Unfortunately, I cannot produce a statically linked executable (as the one provided by rclone) because some of the libraries I'm depending on don't support static linking. For example, libcurl is linked to libkrb5 but it doesn't support static linking anymore (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=439039). I even tried to recompile libcurl, but then I was blocked by p11-kit (https://lists.freedesktop.org/archives/p11-glue/2011-November/000099.html). Sorry, but I don't think I can build a working static executable.
