### ISSUE TITLE
Unorganized Files

### ISSUE THREAD

**Issue by stickenhoffen** [astrada/google-drive-ocamlfuse#238]
Hi, I'm not even sure the API allows it, but I just discovered I have a load of unorganised files (not related to GDO) in Google Drive, only visible with the following search in Drive:

  **is:unorganized owner:me**

Would it be possible to add a feature to show these files, perhaps an .Unorganized folder, similar to .Trash?

Thanks.

**Comment by astrada** [comment]
I just published v0.6.11 (to the beta PPA) where you can access your unorganized files setting the new config option `lost_and_found` to `true`. You will then see a new directory `/lost+found` where you should find all your unorganized files. Warning: fetching those files is slow because there is no direct filter to get them. I have to fetch all files and then filter (client side) to get those without parents. I've also added a `shared_with_me` option to get shared files (that you can see in "Shared with me" section of the web interface).

**Comment by stickenhoffen** [comment]
This is awesome, thank you so much!

**Comment by atomicthumbs** [comment]
this seems to time out (maybe?) with no results when there's a large number of files.

**Comment by astrada** [comment]
If you remount with `-debug`, do you get any error in the log files?
