### ISSUE TITLE
Cache files too large?

### ISSUE THREAD

**Issue by Windywind** [astrada/google-drive-ocamlfuse#254]
Hi Strada,

I am back again~

I've got a limited storage on my server, 20GB, except the system and all the software I am using, I got around 15GB left. 

So, when I mounted my google-drive onto my machine, I thought I could use it for downloading large files. But, seems things are not going as well as expected. The cache folder could be as big as enough to occupy all the space left, several seconds ago, I deleted the 2.6GB cache folder :( 

And therefore it also may lock some processes, make even `df -h` or `ll` not working. The only thing I can do is to reboot my server, which is not good for me.

So, is there anything I can do with this?

Thanks!

**Comment by astrada** [comment]
Sorry, but if you need to upload big files to Google Drive, there is no way to avoid file caching. So, if you upload files bigger than `max_cache_size_mb`, the file will copied anyway to the cache before uploading (and it will be removed only when completely uploaded). Otherwise, if your files are already in Drive and you just need to stream them, you can set `stream_large_files=true` and files bigger than `large_file_threshold_mb` won't be downloaded to the local cache.

**Comment by Windywind** [comment]
Then, what if I set `max_cache_size_mb` to big enough, say 1000GB, and my BitTorrent application is writing into the mount point? What would happen? Is this a solution to avoid caching?

P.S. In the original post, by "downloading", I mean downloading from the Internet to my Linux machine. (And with google-drive mounted, the application is writing into the mount point, so, that would be an upload to the google-drive)

**Comment by astrada** [comment]
> Then, what if I set `max_cache_size_mb` to big enough, say 1000GB, and my BitTorrent application is writing into the mount point? What would happen? Is this a solution to avoid caching?

Yes, but you should also set `metadata_cache_time` to a big number (say 36000 = ten hours) otherwise your torrent will be downloaded/reuploaded every 60 seconds. Moreover, I don't think this is the ideal scenario I had in mind when developing my application. If you only need to upload big files to the cloud, probably you should check other Drive clients (maybe rclone).

**Comment by Windywind** [comment]
As I said, I don' have a large storage on my server. 

What I want is, the BT client be able to write directly into the mount point (my google drive). So, it's not as simple as uploading a big file, but real-time writing.

And is there's a way to limit the cache size? If so, then I think that would be a solution, right?

**Comment by astrada** [comment]
> And is there's a way to limit the cache size? If so, then I think that would be a solution, right?

Not for uploading. The Drive API doesn't allow to upload only a chunk of a file, so I have to store the whole file in the local cache before uploading it. There is no workaround. Maybe other clients use a different approach and have a solution that fits best your requirements.
