### ISSUE TITLE
Caching before upload is very slow

### ISSUE THREAD

**Issue by fjen** [astrada/google-drive-ocamlfuse#308]
File are written to the cache before the real upload starts. The problem is that this caching reaches only ~2 MB/s and therefor takes a very long time.
After turning on the debug mode, it appears that the local database is queried and updated after every 128k.

This repeats in the logfile for every 128k:
```
[28.453607] TID=88: write /gocryptfs [131072 bytes] 5111808 0
[28.453629] TID=88: BEGIN: Getting metadata from context
[28.453640] TID=88: END: Getting metadata: Valid
[28.453651] TID=88: BEGIN: Loading resource /gocryptfs (trashed=false) from db
[28.454181] TID=88: END: Loading resource /gocryptfs (trashed=false) from db: Found (id=2, state=ToUpl
oad)
[28.454724] TID=88: BEGIN: Writing local file (path=/gocryptfs, trashed=false)
[28.454965] TID=88: END: Writing local file (path=/gocryptfs, trashed=false)
[28.454980] TID=88: BEGIN: Updating resource in db (id=2, state=ToUpload)
[28.516588] TID=88: END: Updating resource in db (id=2)
[28.516612] TID=88: BEGIN: Updating cache size (delta=131072) in db
[28.577785] TID=88: END: Updating cache size (new size=5242880) in db
[28.578019] TID=89: getxattr /gocryptfs security.capability
[28.578041] TID=89: BEGIN: Getting metadata from context
[28.578053] TID=89: END: Getting metadata: Valid
[28.578064] TID=89: BEGIN: Loading resource /gocryptfs (trashed=false) from db
[28.578612] TID=89: END: Loading resource /gocryptfs (trashed=false) from db: Found (id=2, state=ToUpl
oad)
```

Is there a way to speedup this process?

**Comment by astrada** [comment]
No sorry, you should patch your kernel and libfuse (see issue #128). Or maybe you can try another client, like rclone that AFAIK caches everything in RAM so it should be faster.

**Comment by fjen** [comment]
The question is whether the database updates are really necessary. I think they contribute in a significant way to this slow behaviour.
Rclone unfortunately doesn't support other fuse filesystems (enfs, gocryptfs) above it.

**Comment by vi** [comment]
`eatmydata google-drive-ocamlfuse` makes upload fast.

**Comment by astrada** [comment]
In version 0.7.1, I added a new config option (`write_buffers`). If you turn it to `true`, it caches files in memory before uploading. It should speed up uploads. It's still experimental, so turn it on at your risk. :wink:

**Comment by vi** [comment]
Does it stop doing `fsync` for each uploaded file (or part of a large file)?

**Comment by astrada** [comment]
It writes to the filesystem only when there are no more free buffers (`max_memory_cache_size` is the total cache size and `memory_buffer_size` is the size of single buffers). Since version 0.7.0, the writes to the sqlite3 db are also cached in memory and flushed every `metadata_memory_cache_saving_interval` seconds.

**Comment by astrada** [comment]
And in version 0.7.10, I've added `async_upload_queue` config option to start async uploads.

**Comment by ghost** [comment]
I experienced the same thing with the latest version of google-drive-ocamlfuse (0.7.30) on Ubuntu 22.04.3 (kernel 6.2.0-36-generic #37~22.04.1-Ubuntu).
When I start copying files from the Google-Drive-mounted directory (using rclone or rsync), google-drive-ocamlfuse starts to download files from Google Drive at the max bandwidth (70 MBit in my case). However, at the client side (rclone reading from the mounted share), I only get 100-200 kByte/sec. 

This seems to be an issue with the caching system from google-drive-ocamlfuse that does not seem to work optimally.
As soon as I turn off caching, by setting `max_memory_cache_size` to 0 (0 MByte file size limit for caching), I get a significant speed increase. Suddently, the 100-200 kByte/sec become ~1000 kByte/sec. Still that is quite slow as Google Drive should easly be able to provide >5 MByte/sec. I did need to set `stream_large_files=true` to obtain this. Also, the total file-copying experience suddenly becomes significantly more snappier.
I have played with all cache/stream options before and they all did not seem to matter much, as any change never got me speeds >300 kByte/sec.

Now, disabling cache seems to work, but google-drive-ocamlfuse still crashes after every ~1.5h of syncing.
I have spent several hours already on debunking why I get such extremely slow transfer timse (while google-drive-ocamlfuse uses full network bandwidth in the background when talking to Google Drive).
Any tips or ideas are more than welcome!

**Comment by ghost** [comment]
Great! I finally found out that you can also configure "Google Drive" in `rclone` separately from `google-drive-ocamlfuse`. I was using `rclone` on top of a folder mounted using `google-drive-ocamlfuse`, which apparently makes for a non-optimal joint solution. Now getting max-bandwidth file transfers using `rclone` alone... 
Leaving this here for anyone trying to do the same in the future... The obvious things are often not documented!

**Comment by ghost** [comment]
Summary after spending hours in trying different settings of both google-drive-ocamlfuse and rclone.
I leave this here in this thread as this was the thread I ended up in after debugging sigifnicant time.
Hope this helps for other people with the same goal and issues.

In order to copy data from/to Google Drive under Linux:
There are basically two tools you can use, and you should use them separately (not together!):

1. Use the FUSE mount system google-drive-ocamlfuse, which mounts the Google Drive to a local folder. From then on, you can browse it like a local folder and copy-paste files (to/from your local filesystem). I did find this not very snappy and transfer times were a bit disappointing. Using rsync to copy complete folders to the local filesystem was one depressing action, speeds of max 300 kbyte/sec... Use this if you want to occasionally copy a file from/to local file system and Google Drive. To get faster speeds and a snappier behaviour, there are several settings to optimize. Don't try to even go there. If you want to copy file in bulk, go directly for option 2: rclone.

2. Use rclone (basically a fancier version of rsync) to synchronize (both ways) or copy data from/to Google Drive. No browsing, just a single manually started sync/copy action. This works like a charm and fills your complete network bandwidth. You should configure your Google Drive as described here, and then it works out-of-the-box: https://rclone.org/drive/

NOTE: The mistake I initially made was using option 1 and 2 at the same time, so mounting Google Drive using google-drive-ocamlfuse and then running a copy action to a local filesystem using rclone. This works, but is slow and crashes after ~1 hour of copying. Using rclone's built-in Google Drive support makes the use of google-drive-ocamlfuse basically redundant.
