### ISSUE TITLE
google-drive-ocamlfuse ramdomly disconnect

### ISSUE THREAD

**Issue by xxx31fr** [astrada/google-drive-ocamlfuse#351]
Hello,
As i said in the title, the google-drive package disconnect ramdomly.
i can't say after a lenght or other.
But, I'd like to know if it's possible to limit the bandwith up/down with google-drive-ocamlfuse.

Thanks

**Comment by astrada** [comment]
> But, I'd like to know if it's possible to limit the bandwith up/down with google-drive-ocamlfuse.

Yes, there are `max_download_speed` and `max_upload_speed` [config](https://github.com/astrada/google-drive-ocamlfuse/wiki/Configuration) options.

**Comment by Mettcr3w** [comment]
Hi!
I ran into the same issue. The google drive mount disconnects randomly after some activity and I guess it has something to do with API limits, but I cannot prove this.
Do you have any idea how to fix it?

**Comment by astrada** [comment]
You should turn on logging (with `-debug`) and then check the log files to see what kind of errors are you getting.

**Comment by Mettcr3w** [comment]
Hello @astrada !
I already did and at the time of occurence there are no abnormalities.
I'm using the mount point with my Plex Media Server to stream my videos and share it with my family/friends. In exceptional cases it can happen, that there are watching 4 or more people simultaneously.

I grepped for "error" in the debug log and somewhere in the middle something like this appears:
`[4363.465699] TID=144622: Retrying (2/8) final_step after exception: Failure("Sqlite3 error: BUSY")
[4363.497676] TID=144621: Retrying (2/8) final_step after exception: Failure("Sqlite3 error: BUSY")
[4363.752216] TID=144620: Retrying (2/8) final_step after exception: Failure("Sqlite3 error: BUSY")`

But I guess it has nothing to do with my problem and it is just a temporary error, because the mount point is crashing much later (with no clear reason).

**Comment by Crenor** [comment]
I am getting disconnects - and/or it just stops working. Not hitting the API limit, I just have to do a fuse disconnect and then re-connect and it works again.
My issue is it looks to be working, I try to get a file, it downloads some, then just stops.
I have a script to check to re-connect if it is disconnected, but I don't have anything for stops working, but looks ok...

This is so far only happening when I do a large scan of a folder with +1000 items.

**Comment by astrada** [comment]
Should be fixed in the latest versions.
