### ISSUE TITLE
How can I access to the folder created by Backup and Sync

### ISSUE THREAD

**Issue by yamagiraffe** [astrada/google-drive-ocamlfuse#380]
Hi, I'm using google-drive-ocamlfuse on Xubuntu 16.04 to access my Gdrive and everything works well so far. But is there any way to access the the folders on Gdrive created by Backup and Sync(circled in the attached picture)?  

It seems that google-drive-ocamlfuse only mount the areas under My Drive and the backup folders I want to access are not under the My Drive(actually they are not shown after Gdrive is mounted correctly). Of course I know that I can copy these backup folders to the My Drive area manually, but it's gonna be convenient if I could directly access to these backup folders through google-drive-ocamlfuse.

If anybody knows the clue to fix it, please comment on this issue.
![default](https://user-images.githubusercontent.com/34579651/34052381-792cf0ca-e205-11e7-8708-c82ad902711f.PNG)

**Comment by astrada** [comment]
I think you should be able to set `root_folder=` to the root folder id you can see in the [web interface](https://cdn.arstechnica.net/wp-content/uploads/2017/07/Rons_MacBook_Pro_-_Google_Drive_-_Google_Chrome-43.png). Remember to remount with `-cc` since you changed the root folder, or to use a new label.
