### ISSUE TITLE
Strategy for renaming duplicate filenames

### ISSUE THREAD

**Issue by ArminXG** [astrada/google-drive-ocamlfuse#390]
What is the strategy/rule for the changed filename on duplicates?
It seems depending on the filename or other property like type, it differs.

For example, I uploaded files created by duplicity which has filenames like
`duplicity-new-signatures.20141231T230000Z.to.20150131T230000Z.sigtar.gpg`

Sometimes a duplicate it shown with the brackets at the end:
`duplicity-new-signatures.20141231T230000Z.to.20150131T230000Z.sigtar.gpg (2e418022)`

and sometimes it is in the middle:
`duplicity-new-signatures.20141231T230000Z (986c90ff).to.20150131T230000Z.sigtar.gpg`

Can this be changed to like always at the end?
And why is a space added? Space in filenames in Unix/Linux is not nice ;-)

**Comment by astrada** [comment]
Unfortunately the algorithm is quite complicated. I use the field `fullFileExtension` (see https://developers.google.com/drive/v3/reference/files), that's basically what Drive API thinks the full extension is. I didn't use `fileExtension` because this way you don't correctly detect files like `.tar.gz`, `.tar.xz` and so on. If you enable logging you should see lines beginning with `Filename collision detected:` and maybe you get a hint at how the collision is resolved. If you read OCaml, you can find the algo in function `disambiguate_filename` of file `drive.ml`.

> And why is a space added? Space in filenames in Unix/Linux is not nice ;-)

Because this is what Chrome/Chromium does :wink:.
