### ISSUE TITLE
Why not make cached files available offline?

### ISSUE THREAD

**Issue by guestname** [astrada/google-drive-ocamlfuse#395]
Hello,

I've seen the other closed issues on this same subject, but it would be great if there was this option. Is there a specific reason not to implement this? If the files are already cached, what is the point of not letting the user open them?

**Comment by astrada** [comment]
Because it would be a nightmare to re-synchronize after you get back online. Anyway you can emulate that scenario putting a very high number in `metadata_cache_time`.

**Comment by cpassos** [comment]
What about turning the files read-only once you go offline?

**Comment by YipYup** [comment]
@guestname You would still have potentially "missing" files that weren't cached. Depending on programs you use to access your mount, this could cause undesired behavior. Imagine a database engine which is accessing a single database spanned over multiple flat files. If a few flat files were missing (due to being offline), and only some parts of it were cached, your program could behave very unexpectedly. It's almost safer to present all or nothing, as it is ultimately up to individual applications for how they would handle the scenario of a missing file. Since there is no guaranteed commonality, the best universal option for @astrada is to offer it as Online, or Offline and unavailable -- the same behavior a typical volume mount would follow. Then the application itself accessing the volume can decide how to handle the volume state.
