### ISSUE TITLE
Losing Connection to GDrive | Transport endpoint is not connected | CURLE_OPERATION_TIMEOUTED

### ISSUE THREAD

**Issue by Theumis** [astrada/google-drive-ocamlfuse#420]
Hi everyone,

some days ago I had to setup my server because of a HDD failure. So I had to reinstall google-drive-ocamlfuse (0.6.24) and everything for using Plex.
Beforehand I had no problems connecting to GDrive and it ran constantly. But now I often run into the issue, that GDrive isn't connected to the mounting point and when I try to access it, I get the error "Transport endpoint is not connected".
So I started google-drive-ocamlfuse with -verbose and after a day or so it happened again. Because of some issues posted here I know what to search for and I found the error "CURLE_OPERATION_TIMEOUTED". So I edited the config file to timeout after 50000 ms.

This is my config:

apps_script_format=json
apps_script_icon=
async_upload=true
cache_directory=/tmp/gdrive-cache
client_id=XXX.apps.googleusercontent.com
client_secret=XXX
connect_timeout_ms=50000
curl_debug_off=false
data_directory=
delete_forever_in_trash_folder=false
docs_file_extension=true
document_format=odt
document_icon=
download_docs=true
drawing_format=png
drawing_icon=
form_format=zip
form_icon=
fusion_table_format=desktop
fusion_table_icon=
keep_duplicates=false
large_file_read_only=true
large_file_threshold_mb=16
log_directory=
lost_and_found=false
low_speed_limit=0
low_speed_time=0
map_format=desktop
map_icon=
max_cache_size_mb=512000
max_download_speed=0
max_memory_cache_size=1073741824
max_retries=8
max_upload_chunk_size=1099511627776
max_upload_speed=0
memory_buffer_size=8388608
metadata_cache_time=60
presentation_format=pdf
presentation_icon=
read_ahead_buffers=5
read_only=false
root_folder=
shared_with_me=false
spreadsheet_format=ods
spreadsheet_icon=
sqlite3_busy_timeout=5000
stream_large_files=true
team_drive_id=
umask=0o022
verification_code=

And this is the error code I found in gdfuse.log:

[274.381999] TID=48438: Broadcasting streaming error (buffer id=109, state=Error(Failure("Code: 28, Description: CURLE_OPERATION_TIMEOUTED, ErrorBuffer: Resolving timed out after 5513 milliseconds\n")))
[274.382186] TID=48438: Error during request: Code: 28, Description: CURLE_OPERATION_TIMEOUTED, ErrorBuffer: Resolving timed out after 5513 milliseconds
Streaming error (buffer id=109, state=Error(Failure("Code: 28, Description: CURLE_OPERATION_TIMEOUTED, ErrorBuffer: Resolving timed out after 5513 milliseconds\n")))
[274.382368] TID=48762: Streaming error (buffer id=109, state=Error(Failure("Code: 28, Description: CURLE_OPERATION_TIMEOUTED, ErrorBuffer: Resolving timed out after 5513 milliseconds\n")))
[274.382432] TID=48761: Error during request: Code: 28, Description: CURLE_OPERATION_TIMEOUTED, ErrorBuffer: Resolving timed out after 5513 milliseconds
[274.382479] TID=48762: Error during request: Code: 28, Description: CURLE_OPERATION_TIMEOUTED, ErrorBuffer: Resolving timed out after 5513 milliseconds
[318.497852] TID=53574: Broadcasting streaming error (buffer id=60, state=Error(Failure("Code: 28, Description: CURLE_OPERATION_TIMEOUTED, ErrorBuffer: Resolving timed out after 5514 milliseconds\n")))
[318.497902] TID=53897: Streaming error (buffer id=60, state=Error(Failure("Code: 28, Description: CURLE_OPERATION_TIMEOUTED, ErrorBuffer: Resolving timed out after 5514 milliseconds\n")))
[318.497985] TID=53574: Error during request: Code: 28, Description: CURLE_OPERATION_TIMEOUTED, ErrorBuffer: Resolving timed out after 5514 milliseconds
[318.498055] TID=53897: Error during request: Code: 28, Description: CURLE_OPERATION_TIMEOUTED, ErrorBuffer: Resolving timed out after 5514 milliseconds
[318.498141] TID=53898: [318.498124] TID=53897: Streaming error (buffer id=60, state=Error(Failure("Code: 28, Description: CURLE_OPERATION_TIMEOUTED, ErrorBuffer: Resolving timed out after 5514 milliseconds\n")))
[318.498356] TID=53898: Error during request: Code: 28, Description: CURLE_OPERATION_TIMEOUTED, ErrorBuffer: Resolving timed out after 5514 milliseconds

So was it a good choice to increase the timeout int? What may I do if it happens again? Was the issue in general the timeout int?

**Comment by Theumis** [comment]
To update my issue: I still get the error "Transport endpoint is not connected" randomly but I can't find the CURLE_OPERATION_TIMEOUTED in the gdfuse.log anymore.
But what could be the problem, that google-drive-ocamlfuse is disconnecting nearly every day?

**Comment by KharmaScribbles** [comment]
I have been using GDrive *daily* for the past month or more, manually mounting it with the same command after each boot. Made an alias, everything worked fine, I have had no problems saving to it locally, remotely, other programs reading or writing to it worked great etc.  All of a sudden today, April 25, I am getting the same error as above about "Transport endpoint not connected" when I run my mount command.  When I run the command terminal appears to complete successfully, as terminal just prompts me with a new line as usual.  
 
However, starting today, after attempting to mount GDfuse my entire Thunar file manager freezes up and eventually produces an error that it can't open my home directory because of the unconnected endpoint related to my GDfuse mountpoint. When the error in Thunar displays, I can see my mountpoint for GDfuse created and appears mounted, but if I click on the Unmount button I get an error that it can't unmount, because of a missing end point. I can not browse to it either.

My audio programs like Cmus and Mocp also can not read my home dir, they freeze and never complete so I have to kill their processes.

Numerous reboots.
Nothing at all in the log.
My cache file in .gdfuse was insanely huge, but even after deleting the contents and rebooting I still receive the error, so probably not related.

Ubuntu 16.04

**Comment by rowanpi** [comment]
This is also happening to me. Ubuntu 16.04

**Comment by metaMMA** [comment]
Same in Ubuntu 19.04. No lines have been written to `gdfuse.log`

**Comment by metaMMA** [comment]
I just tried connecting the usual way, but from a public library. The google drive connected just fine. This makes me believe the issue may be related to DNS resolution. 

It's just a guess, but try changing the nameservers located in `/etc/resolv.conf` id on a Debian-based system.

Here are some guides, if you're unfamiliar with the process:
[Ubuntu: Set OpenDNS DNS Server](https://web.archive.org/web/20190711205207/https://support.opendns.com/hc/en-us/articles/228007087-Ubuntu)
[ OpenDNS Device Configuration - Ubuntu](https://web.archive.org/web/20190711205241/https://www.dnsknowledge.com/tutorials/opendns/ubuntu-linux-opendns-command-line-options/)

**Comment by rowanpi** [comment]
I eventually un-installed, and re-mounted the drive then it worked

**Comment by GhyslainBruno** [comment]
Any news about that issue ? 

Getting the same error after some days (or after some long watching of long files) for me. 

Using it with Plex,
On Ubuntu server 18.04

**Comment by progressify** [comment]
> Any news about that issue ?
> 
> Getting the same error after some days (or after some long watching of long files) for me.
> 
> Using it with Plex,
> On Ubuntu server 18.04

have you found a solution? I have the same use case (plex + gdrive)

**Comment by GhyslainBruno** [comment]
@progressify kind of. 

[Here is](https://github.com/astrada/google-drive-ocamlfuse/issues/281#issuecomment-553480626) the comment I left in the [#281](https://github.com/astrada/google-drive-ocamlfuse/issues/281) closed issue. 

Since I made that, it worked all the time (about a year now). 

Plex + Google drive is definitely a great setup.

**Comment by progressify** [comment]
wow thankyou @GhyslainBruno! I have applied your configuration and reading all the discussion I have found my problem..
I have my setup on a small vps with only 1Gb of ram. I have configured a smaller buffer and now with your fix and a little tuning in the config file my setup work fine! <3
