### ISSUE TITLE
Performance bug ls on teamdrive

### ISSUE THREAD

**Issue by coretemp** [astrada/google-drive-ocamlfuse#464]
Using google-drive-ocamlfuse version 0.6.25,  I expect that running `ls` after an initial installation runs in less than one second. In reality it was around 5 minutes or so on a 1 Gb-internet connection. 

Failing that, please document specific reasons as to why your tool is the best that can theoretically be achieved, because your current communication seems to have been vague on this point. 

The number of files in that directory was only 5 or so.

**Comment by coretemp** [comment]
I was aware that https://github.com/astrada/google-drive-ocamlfuse/issues/58 existed, but it is 4 years old. 

My opinion of this tool currently is that it has *negative* value. I.e., if it hadn't existed, I wouldn't have wasted time to set it up. 

My best result was to do a partial directory listing with `ls` that took ten minutes with an I/O error on top. This includes following all the relevant suggestions I have seen.  

This seems to match the experience of others. The S3 fuse package doesn't have these terrible slow speeds. Sure, the backends are different, but both use FUSE. So, unless you are saying it's Google, it just seems your application is the cause.

I think you should actually warn people with a big disclaimer that for team drives it essentially doesn't work. 

Perhaps it's just me, but I don't see the point of publishing software under your name when it is this bad.

**Comment by dougstarfish** [comment]
I'm seeing horrible slowness that I can quantify as well. Take a look at this stat output from debian. The average stat time per file is 3-5 seconds, though sometimes it speeds up for a little while for no apparent reason. This does not get matched by tshark performance, so whatever the slowness is, it doesn't look like it's in the network access from the fuse agent to google drive. Tshark is mostly idle most of the time and the slowness appears to be in the fuse layer, but not fuse itself, because I have another fuse network app that can access S3 buckets at 30,000 stats/sec.

lstat("/mnt/starfish-team-sales/Sales Archive/Enrico Palmerino archive/Quotes/Starfish Bayer Quote File System Analyzer.ods", {st_mode=S_IFREG|0444, st_size=76984, ...}) = 0 <4.518065>
lstat("/mnt/starfish-team-sales/Sales Archive/Enrico Palmerino archive/Quotes/Drexel University Quote.ods", {st_mode=S_IFREG|0444, st_size=76229, ...}) = 0 <5.159174>
lstat("/mnt/starfish-team-sales/Sales Archive/Enrico Palmerino archive/Quotes/Genentech Starfish Quote 10.10.17.ods", {st_mode=S_IFREG|0444, st_size=78125, ...}) = 0 <4.556196>
lstat("/mnt/starfish-team-sales/Sales Archive/Enrico Palmerino archive/Quotes/WPI Quote 10.10.2017.ods", {st_mode=S_IFREG|0444, st_size=77096, ...}) = 0 <3.954555>
lstat("/mnt/starfish-team-sales/Sales Archive/Enrico Palmerino archive/Quotes/AMD Starfish Quote Option 1.ods", {st_mode=S_IFREG|0444, st_size=76863, ...}) = 0 <5.406171>
lstat("/mnt/starfish-team-sales/Sales Archive/Enrico Palmerino archive/Quotes/AMD Starfish Quote Option 2.ods", {st_mode=S_IFREG|0444, st_size=76968, ...}) = 0 <4.498987>
lstat("/mnt/starfish-team-sales/Sales Archive/Enrico Palmerino archive/Quotes/NREL Starfish Quote 10.10.17.ods", 

Any thoughts on what's going on?

**Comment by astrada** [comment]
> Any thoughts on what's going on?

You are accessing Google Docs. These files have to be exported, because their native format is unavailable to the API. So what happens in practice is that these files are downloaded even to get the file size (stat). That's because it's not possible to know the exported file size before downloading them.

**Comment by dougstarfish** [comment]
wow, that would explain it..  ouch.

**Comment by dougstarfish** [comment]
Is there a reason you aren't using the drive v2 list method for the list callback in fuse instead of trying to download? https://developers.google.com/drive/api/v2/reference/files/list

**Comment by astrada** [comment]
I'm actually using that method, but there is a problem with the exported documents. The API returns a size of 0 for those files, so if I don't download them before returning the actual size to the operating system, they will remain 0-sized and the SO would treat them as empty files. If you don't need to access those files, you can set `download_docs=false` (in `config`) and they will be treated as empty files, this way performances will improve a lot.

**Comment by dougstarfish** [comment]
Oh, that's really odd.... I wonder if we should file a bug with google docs team?

**Comment by astrada** [comment]
I don't think they can do very much about it. The file size depends on the export format, an `.ods` is different from a `.doc`, so they can't send a correct size beforehand. The problem is more on the FUSE side.

**Comment by astrada** [comment]
Since v0.7.5, the new default is to get a link to Google Docs instead of exporting them (see https://github.com/astrada/google-drive-ocamlfuse/wiki/Usage#options). This should increase performances.
