### ISSUE TITLE
how do I stop it?

### ISSUE THREAD

**Issue by themaddoctor** [astrada/google-drive-ocamlfuse#468]
Several read and ls and rm processes are hung. I killed the terminal sessions to which they belong, but those processes are still running. I have tried every kill signal available, from user and from root, but they will not stop. I cannot unmount the google drive while these processes are running. I cannot kill goog-drive-ocamlfuse either.

**Comment by Nate872711** [comment]
try "fusermount -zu /locationofmount"

**Comment by rayhogenson** [comment]
I believe I am experiencing the same issue. I have google-drive-ocamlfuse installed from the beta PPA.

The issue can be reliably reproduced by running
`truncate -s 50G ~/drive/test`, which I would expect to take a while, it's uploading 50 gigabytes after all, but what I don't expect is I can't kill the truncate process, I can't kill google-drive-ocamlfuse while it's hung. Of course, I can't unmount either.

And note the problem doesn't just occur when I truncate files, random processes get hung as OP describes, but truncate is the most reliable way I've found to demonstrate the issue. Let me know if you want logs.

**Comment by astrada** [comment]
You can kill the process anyway using `kill -9`. The mount point will be left in an error state, so you will have to unmount it with `fusermount -u`. The problem is that uploading begins when files are closed/released, and in a local file-system, that operation should be very quick. In a previous version the upload process was handled asynchronously but that increased the probability of having data inconsistencies server side.
