### ISSUE TITLE
Large read/writes causes hard system crash

### ISSUE THREAD

**Issue by bkayes** [astrada/google-drive-ocamlfuse#518]
EDIT: submitted too soon. I'll add my debug info in a minute.
My use case is that I need to be able to upload/download several 1 GB files to google drive. I made a program that fills 5-10 files with 1 GB worth of random characters, and writes it to the mounted google drive. This operation frequently hard crashes my entire system. (The screen goes black and is overall unresponsive, but the system is still on.)
I am able to reproduce the issue when I have 5 1GB files in google drive named "testFile0.txt", "testFile1.txt"... Then I run my program, and it opens "testFile0.txt" for writing. This causes your program to download "testFile0.txt" to the cache so that I can write to it and reupload it. The first two succeed (it downloads and is overwritten), but then once it begins the reupload, it crashes.

I have all of the debug info saved in a file. Let me know if you want this information, and how I can provide it to you. (Maybe over email?)

**Comment by astrada** [comment]
> I have all of the debug info saved in a file. Let me know if you want this information, and how I can provide it to you. (Maybe over email?)

Yes, please, send `gdfuse.log` to my personal email (you can find it in my profile), so I can check if there are any errors. Consider that I start the uploading on file close. That operation is normally considered instantaneous by the SO so it's probably blocking until `close()` returns. I think that is the cause of your system being unresponsive. In old versions (before 0.7) the uploading was asynchronous, so you didn't experienced this issue, but there was a risk of data loss because the file could be modified before the upload ended and those changes would be lost.

**Comment by kwcooper** [comment]
I had a similar problem on Ubuntu 18.04. Copying large files to the mounted drive folder causes the filesystem to freeze, typically towards the last couple mb of the copy (which is slightly frustrating). 

That said, this is a wonderful piece of software (Thank you!)

**Comment by astrada** [comment]
In version 0.7.10 there is a new `async_upload_queue` that should permit async uploads in a safer way.
