### ISSUE TITLE
Is there a method to force the drive to refresh?

### ISSUE THREAD

**Issue by kwcooper** [astrada/google-drive-ocamlfuse#564]
Hello! Thank you for a wonderful piece of software. I searched the wiki and could not find an option to force a mounted drive to refresh to update recently uploaded files that seem to take >5m to appear. Is unmounting and remounting the only option? Thanks!

**Comment by astrada** [comment]
No there is no such option. If you have an old version please update to the latest (0.7.6 stable or 0.7.8 beta) because old versions had that issue. If you are already using the latest version and are able to reproduce your issue with `-debug`, please send your log files to my personal email (alessandro.strada@gmail.com). Thanks!
