### ISSUE TITLE
Manually passing access and refresh token

### ISSUE THREAD

**Issue by doprdele** [astrada/google-drive-ocamlfuse#591]
Is there any way I can pass an access and refresh token on the command line? We have an application that produces these and passes them to RClone which mounts Google Drive, but, we want to try Google Drive OCAMLFuse for better permissions handling.

I didn't see anything in the documentation so I'm  wondering if this is configurable somewhere but not documented

**Comment by astrada** [comment]
You can manually edit `~/.gdfuse/default/state` and put your access token in `last_access_token` and your refresh token in `refresh_token`. And you have to put client id/secret in the config file (or pass them on the command line) otherwise you won't be able to refresh the access token.

> we want to try Google Drive OCAMLFuse for better permissions handling.

Note that permissions are not enforced, they are just kept as metadata for backups.

**Comment by doprdele** [comment]
Great.

> Note that permissions are not enforced, they are just kept as metadata for backups.

The problem we're having is that the executable bit is not kept when mounted as a filesystem. Does ocaml fuse preserve original permissions?

**Comment by astrada** [comment]
> Does ocaml fuse preserve original permissions?

Yes, that should be fine. It just doesn't enforce user/group ACL.
