### ISSUE TITLE
Directory hard links count is incorrect

### ISSUE THREAD

**Issue by g4mba5** [astrada/google-drive-ocamlfuse#595]
Apparently the directory hard link count is always 2, whatever the directory contents is.

The directory hard link count must be 2 plus the number of sub-directories in that directory. Otherwise it breaks the logic of Unix file systems relation between i-nodes and names, and the programs that rely on that logic.

I don't know if this is a problem in `google-drive-ocamlfuse` or in `fuse` directly, neither if this logic is requested by POSIX or is some unofficial implicit behaviour.

**Comment by astrada** [comment]
I misunderstood how that field is calculated. After a bit of googling, it looks like it isn't required by POSIX (btrfs and the majority of FUSE bindings set that value to 1: https://github.com/cryptomator/fuse-nio-adapter/issues/34). I'd rather hard code that value to 1 too, because counting subdirectories means doing an extra request and some special directories (like the shared files one or the lost&found one can contain many files and slow things considerably).
Moreover, It looks like the value 1 can be used to mean "I don't know how many subdirs there are" (https://bugzilla.kernel.org/show_bug.cgi?id=196405#c5).

**Comment by astrada** [comment]
In version 0.7.15, st_nlink is always set to 1.

**Comment by g4mba5** [comment]
Thanks for the fix. This is exactly how I understood the `st_nlink` field:
- `st_nlink` > 2 : the directory has `st_nlink` - 2 sub-directories.
- `st_nlink` = 2 : the directory has no sub-directory.
- `st_nlink` < 2 : non-POSIX file system, number of sub-directories unknown.

I use that in Gambas for recursively scanning directories. Using the information provided by `st_nlink` speeds up the scan a lot. But if this information is false, then the scan is incorrect.

Thanks again and happy new year!
