### ISSUE TITLE
uploaded a video but on gdrive page it says it doesn't exists

### ISSUE THREAD

**Issue by kurokirasama** [astrada/google-drive-ocamlfuse#643]
Hello,
I just installed this tool and i found it amazing. However I have the following issue.

I uploaded a video.
I can watch it just fine on the mounted gdrive. 
On gdrive webpage, when I tried to open it (to watch it online) a message appears saying that the "video doesn't exists" giving me the option to download it. 
I download it, but it came with and extra extension: file.mp4.oBrf9X. I renamed it and could watch it just fine locally.
I also uploaded it through the explorer and I don't have this issue, I could watch it online just fine.
Here there are curl and gdfuse logs. curl.log is 1Gb size so it just let a link here (when it finish uploading):

[gdfuse.log](https://yadi.sk/d/6UpFZ3-4RFCxpw
)
[curl.log](https://yadi.sk/d/6WBpoVAuVQxd8g
)
Regards,

**Comment by astrada** [comment]
The tool you used to upload the video uploaded it as `.Clase012.mp4.oBrf9X` so Google Drive couldn't set the correct MIME type (in the logs you see that the API returned `"mimeType": "application/octet-stream"`). At the end of the upload, the tool renamed the file to `Clase012.mp4`. If you want to keep the preview mode on the web interface you should use a tool that starts the upload with the correct extension, because MIME type cannot be changed once the file has been created.

**Comment by kurokirasama** [comment]
So, I can't use your tool to upload videos? Or should i run with some other parameter?

**Comment by astrada** [comment]
The problem is caused by the tool you are using to copy the video from your local file-system to the mounted GDrive. If you use something like `cp` from terminal, it should work.

**Comment by kurokirasama** [comment]
oooooh ok! lol. I used rsync, because I like to see the progress... I'll have to stick to cp then. Thanks!

**Comment by brancomat** [comment]
> I used rsync, because I like to see the progress... I'll have to stick to cp then.

If you want to use rsync you can simply use the `--inplace` option that avoids the creation of temporary files.

Take a look at [this wiki page](https://github.com/astrada/google-drive-ocamlfuse/wiki/rsync) for other useful rsync options with google-drive-ocamlfuse mounts
