### ISSUE TITLE
Moving files between 2 mounted drives extremely slow (rarely reaches 100kilobytes/s)

### ISSUE THREAD

**Issue by misaalanshori** [astrada/google-drive-ocamlfuse#668]
So I'm trying to move this folder from one google account to another account, so i mounted both accounts and started moving the file, but the speeds are extremely slow, almost never even reaching 100KB/s. I was expecting at least 5MB/s because my VPS has over 100MBit/s Up and Down as tested from Google Speedtest

![image](https://user-images.githubusercontent.com/38964181/97410281-727fc480-1931-11eb-9e12-7dc7aea746ef.png)

I think this folder I'm trying to move has at least 300GB of files on it and with this speed its just gonna take way too long

![image](https://user-images.githubusercontent.com/38964181/97411235-9099f480-1932-11eb-9cf0-c333876440d6.png)

I'm moving the files with mv and checking the % and speed using progress

Is there any way to speed this up? I need at least like 1MB/s to be able to move this folder in a sensible amount of time. it seems like the CPU could be the bottleneck here but I'm not really sure, the google-drive-ocamlfuse process has very high CPU usage on my VPS and sometimes it maxes out to 100%.

![image](https://user-images.githubusercontent.com/38964181/97412000-89271b00-1933-11eb-9e44-f526ec8ea5e9.png)

**Comment by astrada** [comment]
The fastest way to upload a massive number of files is through the web interface. Otherwise you can try setting the experimental option `write_buffers=true` to turn on the memory cache on writes, and play with the settings `memory_buffer_size` and `max_memory_cache_size` to get the optimal throughput for your system. But you can never achieve the web interface performances because the files must be fully copied to cache before uploading them (and that's because how the Drive API works), so in your case with the default options you have to download 300GB to the local cache of the source drive, copy those 300GB to the local cache of the destination drive and then upload 300GB to Drive. I don't know if in this case [rclone](https://github.com/rclone/rclone) is a better solution.

**Comment by misaalanshori** [comment]
In the end I decided to use a third-party website and it worked. but i might try rclone in the future
