### ISSUE TITLE
Questions about duplicate filenames/directory handling

### ISSUE THREAD

**Issue by brancomat** [astrada/google-drive-ocamlfuse#765]
Hi, I searched in the documentation and read issue #390 but I'm not sure about how duplicate names are handled.

Whenever I have a duplicate, the situation is like this:
```
$ ls -lad buttami*
drwxrwxr-x. 1 user group 4096 Mar  8 12:22  buttami
drwxrwxr-x. 1 user group 4096 Mar  8 12:23 'buttami (b2f54385)'
```
1) what's the number between brackets? can I use it somehow to trace the file ID?
2) can I trust that the oldest file will be always the one not renamed?

thanks

**Comment by astrada** [comment]
> what's the number between brackets? can I use it somehow to trace the file ID?

Not directly, the number is the last [n * 8] bytes of the MD5 hash of the remote ID returned by the Drive API, where [n] is the number of conflicts for the same file (and [n] cannot be greater than 4). I implemented it this way, because you can have a file that is named literally [buttami (b2f554385)] in your Drive (e.g., if you copy the file with the duplicated name), so there has to be a way to handle multiple conflicts for the same file.

> can I trust that the oldest file will be always the one not renamed?

No, sorry, it depends on the order of the files returned by the Drive API (it's probably stable, but it's unspecified so you can't bet on it). The order is granted only while the cache is valid.

Sorry, but unfortunately there is no simple way to handle all the edge cases, and this is the simplest way that I came up with.

**Comment by brancomat** [comment]
No problem, thanks a lot for the explanation!
